name: Custom Actions Workflow

on: push

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load & cache dependencies
        id: cached-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false' # Disables caching (this step only)

      - name: Output information # Prints the output value of the custom action
        run: echo "Cache used? ${{ steps.cached-deps.outputs.used-cache }}"

      - name: Lint code
        run: npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Test code
        id: run-tests
        run: npm run test

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json

  build-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps

      - name: Build website
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist

      - name: Output contents
        run: ls

      - name: Deploy site
        id: deployed-website
        uses: ./.github/actions/js-action
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: custom-javascript-action # S3 Bucket Name
          dist-folder: ./dist

      - name: Output website URL
        run: |
          echo "Live URL: ${{ steps.deployed-website.outputs.website-url }}"