name: Issues Workflow

on: issues

jobs:
  issues-job:
    runs-on: windows-latest
    steps:
      - name: Issues Execution
        run: |
          Get-Content $env:GITHUB_EVENT_PATH
        shell: powershell